name: Swift Build Check

on:
  push:
    branches: 
     - main
  pull_request:
    branches:
      - main  # La rama de integración, ajusta según tu configuración

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Swift
      uses: SwiftActions/setup-swift@v1
      with:
        swift-version: '5.5'  # Ajusta la versión de Swift según tu proyecto

    - name: Build Project
      run: swift build

    - name: Test Project
      run: swift test
